=== CopilotIQ/twilio-sdk-go/tools/cli/codegen/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Service Definition Schema",
  "description": "The service definition schema is the definition which all api.json files must comply with in order to be generated via the codegen tooling",
  "required": [
    "packageName",
    "name",
    "documentation",
    "config",
    "subClients",
    "structures"
  ],
  "properties": {
    "packageName": {
      "type": "string",
      "title": "The package name",
      "description": "The name of the package which the client or operation is apart of"
    },
    "name": {
      "type": "string",
      "title": "The client name",
      "description": "The name of the client"
    },
    "documentation": {
      "type": "object",
      "title": "The client or api operation documentation",
      "description": "The documentation which is included with the client or api operation",
      "required": ["description"],
      "properties": {
        "description": {
          "type": "string",
          "title": "The client description",
          "description": "A description of the client"
        },
        "twilioDocsLink": {
          "type": "string",
          "title": "Twilio documentation link",
          "description": "A link to the Twilio documentation"
        }
      }
    },
    "config": {
      "type": "object",
      "title": "The client configuration",
      "description": "The configuration for the client",
      "required": ["beta", "subDomain", "apiVersion"],
      "properties": {
        "beta": {
          "type": "boolean",
          "title": "Is the client in beta",
          "description": "Whether the client and api operation are currently in beta"
        },
        "subDomain": {
          "type": "string",
          "title": "Twilio subdomain",
          "description": "Twilio subdomain for the client"
        },
        "apiVersion": {
          "type": "string",
          "title": "Twilio api version",
          "description": "Version of the Twilio API the client uses"
        }
      }
    },
    "subClients": {
      "type": "array",
      "title": "Array of service sub clients",
      "description": "An array of sub clients for the service",
      "items": {
        "type": "object",
        "title": "Service sub client",
        "description": "Sub clients for the service",
        "required": ["packageName", "name", "documentation", "operations"],
        "properties": {
          "packageName": {
            "$ref": "#/properties/packageName"
          },
          "name": {
            "$ref": "#/properties/name"
          },
          "documentation": {
            "$ref": "#/properties/documentation"
          },
          "subClients": {
            "$ref": "#/properties/subClients"
          },
          "function": {
            "type": "object",
            "title": "Function configuration",
            "description": "Whether the parent client should include a function to initialise the sub client",
            "required": ["parameters"],
            "properties": {
              "parameters": {
                "type": "object",
                "title": "The function parameters",
                "description": "The function parameters which need to be supplied to initialise the sub client",
                "patternProperties": {
                  ".{1,}": {
                    "type": "object",
                    "required": ["dataType"],
                    "properties": {
                      "dataType": {
                        "type": "string",
                        "title": "The property data type",
                        "description": "The property data type"
                      }
                    }
                  }
                }
              }
            }
          },
          "properties": {
            "type": "object",
            "title": "The client fields",
            "description": "A map of fields to include on the client",
            "patternProperties": {
              ".{1,}": {
                "type": "object",
                "oneOf": [
                  {
                    "type": "object",
                    "required": ["dataType", "parentProperty"],
                    "properties": {
                      "dataType": {
                        "type": "string",
                        "title": "The property data type",
                        "description": "The property data type"
                      },
                      "parentProperty": {
                        "type": "string",
                        "title": "The parent property name",
                        "description": "The name of the parent property used to set the field"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": ["dataType", "functionParameter"],
                    "properties": {
                      "dataType": {
                        "type": "string",
                        "title": "The property data type",
                        "description": "The property data type"
                      },
                      "functionParameter": {
                        "type": "string",
                        "title": "The function parameter",
                        "description": "The name of the function parameter used to set the field"
                      }
                    }
                  }
                ]
              }
            }
          },
          "operations": {
            "type": "array",
            "title": "Array of API operations",
            "description": "An array of API operations",
            "items": {
              "type": "object",
              "required": ["name", "http", "documentation"],
              "properties": {
                "name": {
                  "type": "string",
                  "title": "API operation name",
                  "description": "The name of the API operation"
                },
                "http": {
                  "type": "object",
                  "title": "The HTTP client configuration",
                  "description": "The configuration for the HTTP client",
                  "required": ["uri", "method"],
                  "properties": {
                    "uri": {
                      "type": "string",
                      "title": "The operation URI",
                      "description": "The URI of the operation"
                    },
                    "method": {
                      "type": "string",
                      "title": "HTTP method",
                      "description": "The HTTP method to call the Twilio API with"
                    },
                    "pathParams": {
                      "type": "array",
                      "title": "Path parameters array",
                      "description": "Array of path parameters",
                      "items": {
                        "type": "object",
                        "required": ["name", "value"],
                        "properties": {
                          "name": {
                            "type": "string",
                            "title": "Path parameter name",
                            "description": "The name of the path parameter"
                          },
                          "value": {
                            "type": "object",
                            "title": "Path parameter value",
                            "description": "Path parameter value configuration",
                            "required": ["onService", "property", "type"],
                            "properties": {
                              "onService": {
                                "type": "boolean",
                                "title": "Path parameter on parent client",
                                "description": "Whether the path parameter is on the parent client"
                              },
                              "property": {
                                "type": "string",
                                "title": "Name of path parameter property/ field",
                                "description": "Name of path parameter property/ field"
                              },
                              "type": {
                                "type": "string",
                                "title": "Path parameter data type",
                                "description": "The data type of the path parameter"
                              }
                            }
                          }
                        }
                      }
                    },
                    "queryParams": {
                      "type": "array",
                      "title": "Query string parameters array",
                      "description": "Array of query string parameters which can be included in the API call",
                      "items": {
                        "type": "object",
                        "title": "Query string parameter configuration",
                        "description": "Query string parameter configuration",
                        "required": ["name", "type", "required"],
                        "properties": {
                          "name": {
                            "type": "string",
                            "title": "Query string parameter name",
                            "description": "The name of the query string parameter"
                          },
                          "type": {
                            "type": "string",
                            "title": "Query string parameter data type",
                            "description": "The data type of the query string parameter"
                          },
                          "required": {
                            "type": "boolean",
                            "title": "Required query string parameter",
                            "description": "Whether the query string parameter is required"
                          }
                        }
                      }
                    },
                    "overrides": {
                      "type": "object",
                      "title": "HTTP override configuration",
                      "description": "Override client base url",
                      "required": ["subDomain", "apiVersion"],
                      "properties": {
                        "subDomain": {
                          "type": "string",
                          "title": "Twilio subdomain",
                          "description": "Twilio subdomain for the API operation"
                        },
                        "apiVersion": {
                          "type": "string",
                          "title": "Twilio api version",
                          "description": "Version of the Twilio API the API operation uses"
                        }
                      }
                    }
                  }
                },
                "documentation": {
                  "$ref": "#/properties/documentation"
                },
                "input": {
                  "type": "object",
                  "title": "Input struct configuration",
                  "description": "The configuration for the input struct",
                  "required": ["structure", "documentation"],
                  "properties": {
                    "name": {
                      "type": "string",
                      "title": "Struct name override",
                      "description": "The name override of the input struct, if this is not supplied the structure name is prefixed with the operation name"
                    },
                    "structure": {
                      "type": "string",
                      "title": "Structure reference",
                      "description": "The reference to a structure"
                    },
                    "documentation": {
                      "$ref": "#/properties/documentation"
                    }
                  }
                },
                "response": {
                  "type": "object",
                  "title": "Response struct configuration",
                  "description": "The configuration for the response struct",
                  "required": ["structure", "documentation"],
                  "properties": {
                    "name": {
                      "type": "string",
                      "title": "Struct name override",
                      "description": "The name override of the response struct, if this is not supplied the structure name is prefixed with the operation name"
                    },
                    "structure": {
                      "type": "string",
                      "title": "Structure reference",
                      "description": "The reference to a structure"
                    },
                    "documentation": {
                      "$ref": "#/properties/documentation"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "structures": {
      "type": "object",
      "title": "The map of structure",
      "description": "The map of input and response structures",
      "patternProperties": {
        ".{1,}": {
          "type": "object",
          "required": ["type", "properties"],
          "properties": {
            "type": {
              "type": "string",
              "title": "The input or response format type",
              "description": "The input or response format type"
            },
            "properties": {
              "type": "array",
              "title": "Input or response fields",
              "description": "Array of input or response fields",
              "items": {
                "type": "object",
                "title": "Input or response field",
                "description": "Input or response field configuration",
                "oneOf": [
                  {
                    "type": "object",
                    "required": ["name", "type", "value", "required"],
                    "properties": {
                      "name": {
                        "type": "string",
                        "title": "Field name",
                        "description": "The name of the field"
                      },
                      "type": {
                        "type": "string",
                        "title": "Field data type",
                        "description": "The data type of the field",
                        "not": {
                          "enum": ["map", "array"]
                        }
                      },
                      "value": {
                        "type": "string",
                        "title": "API mapping value",
                        "description": "API mapping for the field"
                      },
                      "required": {
                        "type": "boolean",
                        "title": "Required field",
                        "description": "Whether the field is required"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": ["name", "structure", "value", "required"],
                    "properties": {
                      "name": {
                        "type": "string",
                        "title": "Field name",
                        "description": "The name of the field"
                      },
                      "structure": {
                        "type": "string",
                        "title": "Structure reference",
                        "description": "The reference to another structure"
                      },
                      "structureName": {
                        "type": "string",
                        "title": "Structure name override",
                        "description": "Override the name of the structure"
                      },
                      "value": {
                        "type": "string",
                        "title": "API mapping value",
                        "description": "API mapping for the field"
                      },
                      "required": {
                        "type": "boolean",
                        "title": "Required field",
                        "description": "Whether the field is required"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": ["name", "type", "items", "value", "required"],
                    "properties": {
                      "name": {
                        "type": "string",
                        "title": "Field name",
                        "description": "The name of the field"
                      },
                      "type": {
                        "type": "string",
                        "title": "Field data type",
                        "description": "The data type of the field",
                        "enum": ["map", "array"]
                      },
                      "items": {
                        "type": "object",
                        "title": "The structure of each item",
                        "description": "The structure of each item in the array",
                        "oneOf": [
                          {
                            "type": "object",
                            "required": ["type"],
                            "properties": {
                              "type": {
                                "type": "string",
                                "title": "Field data type",
                                "description": "The data type of the field"
                              }
                            }
                          },
                          {
                            "type": "object",
                            "required": ["structure"],
                            "properties": {
                              "structure": {
                                "type": "string",
                                "title": "Structure reference",
                                "description": "The reference to another structure"
                              },
                              "structureName": {
                                "type": "string",
                                "title": "Structure name override",
                                "description": "Override the name of the structure"
                              }
                            }
                          }
                        ]
                      },
                      "value": {
                        "type": "string",
                        "title": "API mapping value",
                        "description": "API mapping for the field"
                      },
                      "required": {
                        "type": "boolean",
                        "title": "Required field",
                        "description": "Whether the field is required"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== CopilotIQ/twilio-sdk-go/definitions/service/monitor/v1/api.json
{
  "packageName": "v1",
  "name": "Monitor",
  "documentation": {
    "description": "Monitor client is used to manage resources for Twilio Monitor"
  },
  "config": {
    "beta": false,
    "subDomain": "monitor",
    "apiVersion": "v1"
  },
  "subClients": [
    {
      "name": "Alerts",
      "packageName": "alerts",
      "documentation": {
        "description": "Client for managing alert resources",
        "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-alert"
      },
      "operations": [
        {
          "name": "Page",
          "http": {
            "uri": "/Alerts",
            "method": "Get",
            "queryParams": [
              {
                "name": "PageSize",
                "type": "int",
                "required": false
              },
              {
                "name": "Page",
                "type": "int",
                "required": false
              },
              {
                "name": "PageToken",
                "type": "string",
                "required": false
              },
              {
                "name": "LogLevel",
                "type": "string",
                "required": false
              },
              {
                "name": "StartDate",
                "type": "time.Time",
                "required": false
              },
              {
                "name": "EndDate",
                "type": "time.Time",
                "required": false
              }
            ]
          },
          "documentation": {
            "description": "retrieves a page of alerts",
            "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-alert#read-multiple-alert-resources"
          },
          "response": {
            "structure": "AlertsPageResponse",
            "documentation": {
              "description": "defines the response fields for the alerts page"
            }
          },
          "pagination": {
            "name": "AlertsPaginator",
            "page": {
              "name": "AlertsPage",
              "nextToken": "PageToken",
              "nextPage": {
                "meta": true,
                "property": "NextPageURL"
              },
              "items": "Alerts",
              "structure": "PageAlertResponse"
            }
          }
        }
      ]
    },
    {
      "name": "Alert",
      "packageName": "alert",
      "function": {
        "parameters": {
          "alertSid": {
            "dataType": "string"
          }
        }
      },
      "properties": {
        "sid": {
          "dataType": "string",
          "functionParameter": "alertSid"
        }
      },
      "documentation": {
        "description": "Client for managing a specific alert resource",
        "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-alert"
      },
      "operations": [
        {
          "name": "Fetch",
          "http": {
            "uri": "/Alerts/{sid}",
            "method": "Get",
            "pathParams": [
              {
                "name": "sid",
                "value": {
                  "onService": true,
                  "type": "string",
                  "property": "sid"
                }
              }
            ]
          },
          "documentation": {
            "description": "retrieves an alert resource",
            "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-alert#fetch-an-alert-resource"
          },
          "response": {
            "name": "FetchAlertResponse",
            "structure": "AlertResponse",
            "documentation": {
              "description": "defines the response fields for the retrieved alert"
            }
          }
        }
      ]
    },
    {
      "name": "Events",
      "packageName": "events",
      "documentation": {
        "description": "Client for managing event resources",
        "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-events"
      },
      "operations": [
        {
          "name": "Page",
          "http": {
            "uri": "/Events",
            "method": "Get",
            "queryParams": [
              {
                "name": "PageSize",
                "type": "int",
                "required": false
              },
              {
                "name": "Page",
                "type": "int",
                "required": false
              },
              {
                "name": "PageToken",
                "type": "string",
                "required": false
              },
              {
                "name": "ActorSid",
                "type": "string",
                "required": false
              },
              {
                "name": "EventType",
                "type": "string",
                "required": false
              },
              {
                "name": "ResourceSid",
                "type": "string",
                "required": false
              },
              {
                "name": "SourceIPAddress",
                "type": "string",
                "required": false
              },
              {
                "name": "StartDate",
                "type": "time.Time",
                "required": false
              },
              {
                "name": "EndDate",
                "type": "time.Time",
                "required": false
              }
            ]
          },
          "documentation": {
            "description": "retrieves a page of events",
            "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-events#read-multiple-event-resources"
          },
          "response": {
            "structure": "EventsPageResponse",
            "documentation": {
              "description": "defines the response fields for the events page"
            }
          },
          "pagination": {
            "name": "EventsPaginator",
            "page": {
              "name": "EventsPage",
              "nextToken": "PageToken",
              "nextPage": {
                "meta": true,
                "property": "NextPageURL"
              },
              "items": "Events",
              "structure": "PageEventResponse"
            }
          }
        }
      ]
    },
    {
      "name": "Event",
      "packageName": "event",
      "function": {
        "parameters": {
          "eventSid": {
            "dataType": "string"
          }
        }
      },
      "properties": {
        "sid": {
          "dataType": "string",
          "functionParameter": "eventSid"
        }
      },
      "documentation": {
        "description": "Client for managing a specific event resource",
        "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-events"
      },
      "operations": [
        {
          "name": "Fetch",
          "http": {
            "uri": "/Events/{sid}",
            "method": "Get",
            "pathParams": [
              {
                "name": "sid",
                "value": {
                  "onService": true,
                  "type": "string",
                  "property": "sid"
                }
              }
            ]
          },
          "documentation": {
            "description": "retrieves an event resource",
            "twilioDocsLink": "https://www.twilio.com/docs/usage/monitor-events#fetch-an-event-resource"
          },
          "response": {
            "name": "FetchEventResponse",
            "structure": "EventResponse",
            "documentation": {
              "description": "defines the response fields for the retrieved event"
            }
          }
        }
      ]
    }
  ],
  "structures": {
    "AlertsPageResponse": {
      "type": "JSON",
      "properties": [
        {
          "name": "Meta",
          "structure": "MetaResponse",
          "value": "meta",
          "required": true
        },
        {
          "name": "Alerts",
          "type": "array",
          "items": {
            "structure": "AlertResponse"
          },
          "value": "alerts",
          "required": true
        }
      ]
    },
    "AlertResponse": {
      "type": "JSON",
      "extends": "BaseResponse",
      "properties": [
        {
          "name": "AlertText",
          "type": "string",
          "value": "alert_text",
          "required": false
        },
        {
          "name": "APIVersion",
          "type": "string",
          "value": "api_version",
          "required": false
        },
        {
          "name": "ErrorCode",
          "type": "string",
          "value": "error_code",
          "required": true
        },
        {
          "name": "LogLevel",
          "type": "string",
          "value": "log_level",
          "required": true
        },
        {
          "name": "MoreInfo",
          "type": "string",
          "value": "more_info",
          "required": true
        },
        {
          "name": "RequestHeaders",
          "type": "string",
          "value": "request_headers",
          "required": false
        },
        {
          "name": "RequestMethod",
          "type": "string",
          "value": "request_method",
          "required": false
        },
        {
          "name": "RequestURL",
          "type": "string",
          "value": "request_url",
          "required": false
        },
        {
          "name": "RequestVariables",
          "type": "string",
          "value": "request_variables",
          "required": false
        },
        {
          "name": "ResourceSid",
          "type": "string",
          "value": "resource_sid",
          "required": true
        },
        {
          "name": "ResponseBody",
          "type": "string",
          "value": "response_body",
          "required": false
        },
        {
          "name": "ResponseHeaders",
          "type": "string",
          "value": "response_headers",
          "required": false
        },
        {
          "name": "ServiceSid",
          "type": "string",
